// Content for the /solutions/[slug] pages. Each entry drives one page.
// `visual` picks the animated hero illustration in SolutionVisuals.jsx.

export const solutions = [
  {
    slug: "website-development",
    name: "Website Development",
    short: "Websites",
    icon: "layout",
    visual: "browser",
    tagline: "Modern, high-converting websites built for growth.",
    title: "Websites that",
    highlight: "win customers",
    intro:
      "Fast, beautiful and SEO-ready websites designed around your brand and built to turn visitors into enquiries — from landing pages to full business sites and online stores.",
    badges: ["Mobile-first", "SEO-ready", "Lightning fast"],
    features: [
      { icon: "palette", title: "Custom UI Design", desc: "On-brand, pixel-perfect designs — never a recycled template." },
      { icon: "mobile", title: "Responsive Builds", desc: "Flawless on phones, tablets and desktops alike." },
      { icon: "bolt", title: "Performance First", desc: "Optimised code and assets for top Core Web Vitals scores." },
      { icon: "search", title: "SEO Foundation", desc: "Clean structure, metadata and schema baked in from day one." },
      { icon: "cart", title: "E-commerce", desc: "Online stores with secure checkout and easy product management." },
      { icon: "gear", title: "Easy to Manage", desc: "Update content yourself with a simple, friendly CMS." },
    ],
    tools: ["Next.js", "React", "Tailwind CSS", "WordPress", "Shopify", "Figma", "Node.js", "Vercel"],
    process: [
      { step: "01", icon: "target", title: "Discover", desc: "Goals, audience, competitors and sitemap." },
      { step: "02", icon: "palette", title: "Design", desc: "Wireframes and high-fidelity UI for approval." },
      { step: "03", icon: "code", title: "Develop", desc: "Responsive, fast build with weekly previews." },
      { step: "04", icon: "rocket", title: "Launch", desc: "Testing, go-live and post-launch support." },
    ],
    benefits: [
      "Designed to convert visitors into leads",
      "Built on modern, scalable technology",
      "Optimised for Google from the start",
      "Secure hosting & SSL setup",
      "Training so your team can update content",
      "Ongoing maintenance available",
    ],
    faqs: [
      { q: "How long does a website take?", a: "Most business websites launch in 3–6 weeks depending on the number of pages and features." },
      { q: "Will my website work on mobile?", a: "Yes — every site we build is mobile-first and tested across phones, tablets and desktops." },
      { q: "Can I update the content myself?", a: "Absolutely. We set up an easy-to-use CMS and walk your team through it." },
      { q: "Do you provide hosting?", a: "We can set up and manage fast, secure hosting for you, or deploy to your existing provider." },
    ],
  },
  {
    slug: "digital-marketing",
    name: "Digital Marketing",
    short: "Marketing",
    icon: "megaphone",
    visual: "chart",
    tagline: "SEO, ads & social media that drive real growth.",
    title: "Marketing that",
    highlight: "drives growth",
    intro:
      "Data-driven campaigns across search, social and paid media that put your brand in front of the right people — and turn attention into measurable revenue.",
    badges: ["Data-driven", "ROI focused", "Monthly reports"],
    features: [
      { icon: "megaphone", title: "Paid Advertising", desc: "Google & Meta ad campaigns engineered to lower cost-per-lead." },
      { icon: "users", title: "Social Media", desc: "Consistent, on-brand content that builds an engaged audience." },
      { icon: "search", title: "Search Marketing", desc: "Be found when customers are actively searching for you." },
      { icon: "mail", title: "Email Campaigns", desc: "Automated flows that nurture leads into customers." },
      { icon: "palette", title: "Content Creation", desc: "Creatives, reels and copy that stop the scroll." },
      { icon: "chart", title: "Analytics & Reporting", desc: "Clear dashboards so you always know what's working." },
    ],
    tools: ["Google Ads", "Meta Ads", "Google Analytics", "Search Console", "Canva", "Mailchimp", "HubSpot", "SEMrush"],
    process: [
      { step: "01", icon: "search", title: "Audit", desc: "Review channels, competitors and current performance." },
      { step: "02", icon: "target", title: "Strategy", desc: "Channel mix, audiences, budget and KPIs." },
      { step: "03", icon: "megaphone", title: "Execute", desc: "Launch campaigns and content on schedule." },
      { step: "04", icon: "growth", title: "Optimise", desc: "Test, measure and scale what works." },
    ],
    benefits: [
      "Campaigns tied to clear business goals",
      "Transparent monthly performance reports",
      "Continuous A/B testing and optimisation",
      "One team across SEO, ads and social",
      "Creative and copy produced in-house",
      "No long lock-in contracts",
    ],
    faqs: [
      { q: "How soon will I see results?", a: "Paid campaigns can generate leads within days; SEO and organic social typically build momentum over 3–6 months." },
      { q: "What budget do I need for ads?", a: "We recommend a starting budget based on your goals and industry, then scale as results come in." },
      { q: "Which platforms do you manage?", a: "Google, Meta (Facebook & Instagram), LinkedIn and YouTube, plus email and SEO." },
      { q: "How do you report results?", a: "You get a clear monthly report covering spend, leads, conversions and next steps." },
    ],
  },
  {
    slug: "mobile-app-development",
    name: "Mobile App Development",
    short: "Mobile Apps",
    icon: "mobile",
    visual: "phone",
    tagline: "Native & cross-platform apps built for scale.",
    title: "Mobile apps your",
    highlight: "users love",
    intro:
      "Beautiful, high-performance iOS and Android apps — from MVP to App Store launch — built with the right technology for your timeline and budget.",
    badges: ["iOS & Android", "Cross-platform", "Store-ready"],
    features: [
      { icon: "mobile", title: "Native & Cross-Platform", desc: "Swift, Kotlin or Flutter — the right stack for your goals." },
      { icon: "palette", title: "Intuitive UX", desc: "Interfaces designed around real user journeys." },
      { icon: "cloud", title: "Backend & APIs", desc: "Secure, scalable backends and third-party integrations." },
      { icon: "lock", title: "Security Built-in", desc: "Encrypted data, secure auth and best-practice storage." },
      { icon: "bolt", title: "Push & Real-time", desc: "Notifications, chat and live updates that keep users engaged." },
      { icon: "rocket", title: "Store Launch", desc: "We handle App Store and Play Store submission end to end." },
    ],
    tools: ["Flutter", "React Native", "Swift", "Kotlin", "Firebase", "Node.js", "Figma", "AWS"],
    process: [
      { step: "01", icon: "target", title: "Plan", desc: "Features, user flows and MVP scope." },
      { step: "02", icon: "palette", title: "Design", desc: "Interactive prototypes you can tap through." },
      { step: "03", icon: "code", title: "Build", desc: "Agile sprints with test builds every week." },
      { step: "04", icon: "rocket", title: "Launch", desc: "Store submission, monitoring and updates." },
    ],
    benefits: [
      "One codebase for iOS & Android when it fits",
      "Clickable prototype before development",
      "Weekly test builds on your own phone",
      "Scalable cloud backend",
      "Analytics and crash reporting set up",
      "Post-launch updates and support",
    ],
    faqs: [
      { q: "Native or cross-platform — which should I choose?", a: "Cross-platform (Flutter / React Native) suits most apps and saves cost; we recommend native when you need deep device features." },
      { q: "How long does an app take?", a: "A focused MVP typically takes 2–4 months; larger apps are delivered in phases." },
      { q: "Will you publish the app to the stores?", a: "Yes — we prepare listings, screenshots and handle the full submission process." },
      { q: "Do you maintain apps after launch?", a: "We offer maintenance plans covering OS updates, bug fixes and new features." },
    ],
  },
  {
    slug: "seo",
    name: "Search Engine Optimization",
    short: "SEO",
    icon: "search",
    visual: "ranking",
    tagline: "Data-driven SEO that grows your organic traffic.",
    title: "Rank higher,",
    highlight: "grow faster",
    intro:
      "Technical, on-page and content SEO that lifts your rankings, brings in qualified organic traffic and keeps compounding month after month.",
    badges: ["Technical SEO", "Content", "Local SEO"],
    features: [
      { icon: "gear", title: "Technical SEO", desc: "Site speed, crawlability, indexing and Core Web Vitals fixes." },
      { icon: "search", title: "Keyword Research", desc: "Target the terms your customers actually search for." },
      { icon: "layout", title: "On-Page Optimisation", desc: "Titles, headings, content and internal links done right." },
      { icon: "pin", title: "Local SEO", desc: "Google Business Profile and local listings that win nearby customers." },
      { icon: "link", title: "Link Building", desc: "Earn high-quality backlinks that build authority." },
      { icon: "chart", title: "Rank Tracking", desc: "Monthly rankings, traffic and conversion reporting." },
    ],
    tools: ["Google Search Console", "Google Analytics", "Ahrefs", "SEMrush", "Screaming Frog", "PageSpeed Insights", "Google Business Profile", "Schema.org"],
    process: [
      { step: "01", icon: "search", title: "Audit", desc: "Full technical and content health check." },
      { step: "02", icon: "target", title: "Keywords", desc: "Research and map keywords to pages." },
      { step: "03", icon: "gear", title: "Optimise", desc: "Fix issues and optimise on-page content." },
      { step: "04", icon: "growth", title: "Grow", desc: "Content, links and monthly reporting." },
    ],
    benefits: [
      "White-hat techniques only",
      "Clear keyword strategy tied to revenue",
      "Technical fixes handled by our developers",
      "Content written by experienced writers",
      "Monthly ranking and traffic reports",
      "Local SEO for location-based businesses",
    ],
    faqs: [
      { q: "How long does SEO take to work?", a: "Most sites see meaningful movement in 3–6 months, with results compounding over time." },
      { q: "Do you guarantee first-page rankings?", a: "No honest agency can guarantee rankings, but we follow a proven, transparent process and report progress monthly." },
      { q: "Do you write the content too?", a: "Yes — our team researches and writes SEO content aligned with your brand voice." },
      { q: "Can you fix my site's technical issues?", a: "Our developers handle technical SEO fixes directly, so nothing gets stuck in hand-offs." },
    ],
  },
  {
    slug: "custom-software",
    name: "Custom Software Development",
    short: "Custom Software",
    icon: "code",
    visual: "code",
    tagline: "Tailored software that fits how your business works.",
    title: "Software built",
    highlight: "around you",
    intro:
      "From internal tools and dashboards to full SaaS platforms — custom software that automates your workflows, connects your systems and scales with your business.",
    badges: ["Web platforms", "Integrations", "Scalable"],
    features: [
      { icon: "gear", title: "Workflow Automation", desc: "Replace spreadsheets and manual steps with smart software." },
      { icon: "layout", title: "Dashboards & Portals", desc: "Admin panels, client portals and real-time reporting." },
      { icon: "link", title: "System Integrations", desc: "Connect CRMs, ERPs, payment gateways and third-party APIs." },
      { icon: "cloud", title: "SaaS Platforms", desc: "Multi-tenant cloud products ready for real customers." },
      { icon: "database", title: "Scalable Architecture", desc: "Robust databases and APIs that grow without a rebuild." },
      { icon: "shield", title: "Ongoing Support", desc: "Monitoring, updates and new features long after launch." },
    ],
    tools: ["Next.js", "Node.js", "Python", "PostgreSQL", "MongoDB", "AWS", "Docker", "REST & GraphQL"],
    process: [
      { step: "01", icon: "target", title: "Analyse", desc: "Map your workflows and requirements." },
      { step: "02", icon: "layout", title: "Architect", desc: "System design, data model and UI plan." },
      { step: "03", icon: "code", title: "Build", desc: "Agile sprints with regular demos." },
      { step: "04", icon: "shield", title: "Support", desc: "Deploy, monitor and keep improving." },
    ],
    benefits: [
      "Built around your exact processes",
      "You own the code and the IP",
      "Secure, role-based access control",
      "Cloud deployment with backups",
      "Clear documentation and handover",
      "Flexible support and feature plans",
    ],
    faqs: [
      { q: "Why custom software instead of off-the-shelf tools?", a: "Custom software fits your exact workflow, removes manual work and scales without per-seat licence costs." },
      { q: "How long does a custom project take?", a: "Most projects take 2–4 months for a first release, delivered in phases so you see value early." },
      { q: "Who owns the code?", a: "You do — full source code and IP are handed over to you." },
      { q: "Can you integrate with our existing systems?", a: "Yes, we regularly integrate with CRMs, ERPs, payment gateways and custom APIs." },
    ],
  },
];

export const getSolution = (slug) => solutions.find((s) => s.slug === slug);
