// Portfolio content for /portfolio, /portfolio/[category] and /portfolio/work/[slug].
//
// IMPORTANT: every project below is a SAMPLE placeholder (`sample: true`), so the
// site never presents invented work as real. Replace each one with a real
// project (name, summary, details, screenshots) and set `sample: false`.
//
// cover.type: "browser" | "dashboard" | "phone" — picks the animated mockup.
// industry: slug from IndustryComponents/industriesData.js
// services: slugs from SolutionComponents/solutionsData.js

export const categories = [
  {
    slug: "website-design",
    name: "Website Design",
    icon: "layout",
    title: "Websites we've",
    highlight: "designed & built",
    intro: "Fast, beautiful, conversion-focused websites for businesses across industries.",
  },
  {
    slug: "web-applications",
    name: "Web Applications",
    icon: "code",
    title: "Web apps that",
    highlight: "run businesses",
    intro: "Platforms, portals and dashboards that automate work and scale with our clients.",
  },
  {
    slug: "mobile-applications",
    name: "Mobile Applications",
    icon: "mobile",
    title: "Mobile apps people",
    highlight: "love to use",
    intro: "iOS and Android apps designed around real user journeys, from MVP to launch.",
  },
  {
    slug: "case-studies",
    name: "Case Studies",
    icon: "briefcase",
    title: "Deep dives into",
    highlight: "our work",
    intro: "The challenge, the solution and the outcome — a closer look at selected projects.",
  },
];

export const projects = [
  {
    slug: "real-estate-project-website",
    sample: true,
    featured: true,
    name: "Real Estate Project Website",
    category: "website-design",
    industry: "real-estate",
    services: ["website-development", "seo", "digital-marketing"],
    platform: "Web",
    cover: { type: "browser", accent: "#FF5F2D" },
    summary: "A premium launch website for a residential project with galleries, floor plans and lead capture.",
    challenge: "The developer relied on printed brochures and portal listings, with no owned channel to showcase the project or capture serious buyer enquiries.",
    solution: "We designed a premium, mobile-first project site with immersive galleries, interactive floor plans, a location map and enquiry forms routed straight to the sales team.",
    features: [
      { icon: "media", title: "Immersive Galleries", desc: "High-impact visuals optimised for fast loading." },
      { icon: "layout", title: "Interactive Floor Plans", desc: "Explore every unit type with ease." },
      { icon: "pin", title: "Location Highlights", desc: "Map with nearby schools, hospitals and transit." },
      { icon: "chat", title: "Instant Enquiries", desc: "Leads sent straight to WhatsApp and email." },
    ],
    outcomes: ["Owned channel for project marketing", "Every enquiry captured and tracked", "Fast, mobile-first experience", "SEO-ready project pages"],
    tech: ["Next.js", "Tailwind CSS", "Vercel", "Google Analytics"],
  },
  {
    slug: "healthcare-clinic-website",
    sample: true,
    featured: false,
    name: "Healthcare Clinic Website",
    category: "website-design",
    industry: "healthcare",
    services: ["website-development", "seo"],
    platform: "Web",
    cover: { type: "browser", accent: "#0c0705" },
    summary: "A trustworthy multi-specialty clinic website with doctor profiles and online appointment booking.",
    challenge: "Patients could only book by phone, front-desk lines were constantly busy, and the clinic was hard to find in local search.",
    solution: "We built a clean, accessible website with doctor and treatment pages, real-time appointment booking and a local SEO foundation.",
    features: [
      { icon: "users", title: "Doctor Profiles", desc: "Specialities, timings and qualifications." },
      { icon: "calendar", title: "Online Booking", desc: "Real-time slots with confirmations." },
      { icon: "heart", title: "Treatment Pages", desc: "Clear, patient-friendly information." },
      { icon: "search", title: "Local SEO", desc: "Optimised for nearby patient searches." },
    ],
    outcomes: ["Appointments bookable 24/7", "Less pressure on the front desk", "Stronger local search presence", "Professional, trusted brand"],
    tech: ["Next.js", "Node.js", "PostgreSQL", "Google Business Profile"],
  },
  {
    slug: "education-institute-website",
    sample: true,
    featured: false,
    name: "Education Institute Website",
    category: "website-design",
    industry: "education",
    services: ["website-development", "digital-marketing"],
    platform: "Web",
    cover: { type: "browser", accent: "#e6481a" },
    summary: "An admissions-focused institute website with course pages, events and an online application form.",
    challenge: "Prospective students struggled to find course details, and admissions enquiries arrived through scattered phone calls and messages.",
    solution: "We created a structured course catalogue, an events and news section and a simple online application flow tied to admission-season campaigns.",
    features: [
      { icon: "cap", title: "Course Catalogue", desc: "Every programme with fees and outcomes." },
      { icon: "mail", title: "Online Applications", desc: "Apply in minutes from any device." },
      { icon: "calendar", title: "Events & News", desc: "Keep students and parents informed." },
      { icon: "megaphone", title: "Campaign Landing Pages", desc: "Built for admission season ads." },
    ],
    outcomes: ["Clear course information in one place", "Structured admission enquiries", "Ready for seasonal campaigns", "Easy content updates for staff"],
    tech: ["WordPress", "Figma", "Google Ads", "Meta Ads"],
  },
  {
    slug: "logistics-tracking-platform",
    sample: true,
    featured: true,
    name: "Logistics Tracking Platform",
    category: "web-applications",
    industry: "logistics",
    services: ["custom-software", "mobile-app-development"],
    platform: "Web + Android",
    cover: { type: "dashboard", accent: "#FF5F2D" },
    summary: "A shipment tracking and dispatch platform with live status for customers and a dashboard for operations.",
    challenge: "Dispatch ran on phone calls and spreadsheets, and the support team spent hours every day answering \"where is my shipment?\".",
    solution: "We built a web platform for dispatch and live tracking, a driver app for status updates and proof of delivery, and a public tracking page for customers.",
    features: [
      { icon: "pin", title: "Live Tracking", desc: "Real-time status for every shipment." },
      { icon: "gear", title: "Smart Dispatch", desc: "Assign jobs to drivers in a click." },
      { icon: "mobile", title: "Driver App", desc: "Routes, updates and proof of delivery." },
      { icon: "chart", title: "Ops Dashboard", desc: "Deliveries and delays at a glance." },
    ],
    outcomes: ["Full visibility of every shipment", "Fewer status calls to support", "Faster dispatching", "Data to improve routes"],
    tech: ["Next.js", "Node.js", "PostgreSQL", "Flutter", "Google Maps API"],
  },
  {
    slug: "debate-tournament-manager",
    sample: true,
    featured: false,
    name: "Debate Tournament Manager",
    category: "web-applications",
    industry: "debate-academy",
    services: ["custom-software", "website-development"],
    platform: "Web",
    cover: { type: "dashboard", accent: "#0c0705" },
    summary: "A tournament management system for registrations, draws, rounds, judging and live results.",
    challenge: "Tournaments were managed manually with spreadsheets, making draws, room allocation and results slow and error-prone.",
    solution: "We built a web app that automates team registration, round draws, judge allocation and score entry, with live public results.",
    features: [
      { icon: "users", title: "Team Registration", desc: "Online sign-up with payments." },
      { icon: "calendar", title: "Automated Draws", desc: "Rounds and rooms generated instantly." },
      { icon: "debate", title: "Judge Ballots", desc: "Scores entered from any device." },
      { icon: "chart", title: "Live Results", desc: "Rankings updated in real time." },
    ],
    outcomes: ["Tournament admin time greatly reduced", "Fewer manual errors", "Live results for participants", "Reusable for every event"],
    tech: ["React", "Node.js", "MongoDB", "AWS"],
  },
  {
    slug: "construction-project-dashboard",
    sample: true,
    featured: false,
    name: "Construction Project Dashboard",
    category: "web-applications",
    industry: "construction",
    services: ["custom-software", "mobile-app-development"],
    platform: "Web + iOS + Android",
    cover: { type: "dashboard", accent: "#e6481a" },
    summary: "A multi-site project dashboard with schedules, budgets, documents and daily site reports.",
    challenge: "Site updates arrived late over calls and chats, and managers had no single view of schedules, costs and documents.",
    solution: "We delivered a central dashboard for schedules, budgets and documents, plus a field app for daily reports and site photos.",
    features: [
      { icon: "calendar", title: "Scheduling", desc: "Milestones across every site." },
      { icon: "dollar", title: "Budget Tracking", desc: "Planned vs actual costs." },
      { icon: "database", title: "Document Hub", desc: "Drawings and approvals in one place." },
      { icon: "mobile", title: "Site Reports", desc: "Daily updates with photos." },
    ],
    outcomes: ["One view of every project", "Real-time updates from site", "Better budget control", "Organised documents"],
    tech: ["Next.js", "Python", "PostgreSQL", "React Native"],
  },
  {
    slug: "fintech-wallet-app",
    sample: true,
    featured: true,
    name: "Fintech Wallet App",
    category: "mobile-applications",
    industry: "fintech",
    services: ["mobile-app-development", "custom-software"],
    platform: "iOS + Android",
    cover: { type: "phone", accent: "#FF5F2D" },
    summary: "A secure digital wallet app with payments, transaction history and real-time alerts.",
    challenge: "The client needed an MVP that felt as trustworthy as a bank app while staying simple enough for first-time users.",
    solution: "We designed a clean, reassuring interface and built a cross-platform app with secure login, payments and instant notifications on a scalable backend.",
    features: [
      { icon: "lock", title: "Secure Login", desc: "Biometric and PIN authentication." },
      { icon: "dollar", title: "Payments", desc: "Send, receive and pay bills." },
      { icon: "chart", title: "Spending Insights", desc: "Clear history and categories." },
      { icon: "bolt", title: "Real-time Alerts", desc: "Instant transaction notifications." },
    ],
    outcomes: ["MVP ready for real users", "Simple, trustworthy UX", "Secure by design", "Scalable backend for growth"],
    tech: ["Flutter", "Node.js", "PostgreSQL", "Firebase", "AWS"],
  },
  {
    slug: "media-streaming-app",
    sample: true,
    featured: false,
    name: "Media Streaming App",
    category: "mobile-applications",
    industry: "media-entertainment",
    services: ["mobile-app-development", "digital-marketing"],
    platform: "iOS + Android",
    cover: { type: "phone", accent: "#0c0705" },
    summary: "A video streaming app with personalised feeds, subscriptions and offline viewing.",
    challenge: "The publisher's audience was growing on social media, but there was no owned platform to keep viewers or earn recurring revenue.",
    solution: "We built a streaming app with personalised recommendations, subscription plans and offline downloads, backed by a social launch campaign.",
    features: [
      { icon: "media", title: "Video Streaming", desc: "Smooth playback on any network." },
      { icon: "spark", title: "Personalised Feed", desc: "Content picked for each viewer." },
      { icon: "dollar", title: "Subscriptions", desc: "Flexible plans with secure billing." },
      { icon: "cloud", title: "Offline Viewing", desc: "Download and watch anywhere." },
    ],
    outcomes: ["An owned channel for the audience", "Recurring subscription revenue", "Higher viewer engagement", "Launch campaign across social"],
    tech: ["React Native", "Node.js", "AWS", "Stripe"],
  },
];

export const getCategory = (slug) => categories.find((c) => c.slug === slug);
export const getProject = (slug) => projects.find((p) => p.slug === slug);

// Case studies = featured projects.
export const projectsInCategory = (slug) =>
  slug === "case-studies"
    ? projects.filter((p) => p.featured)
    : projects.filter((p) => p.category === slug);
