// Content for the /industries/[slug] pages. Each entry drives one page.
// `services[].solution` must match a slug in SolutionComponents/solutionsData.js.

export const industries = [
  {
    slug: "real-estate",
    name: "Real Estate",
    icon: "building",
    tagline: "Property portals, CRMs and marketing that sell faster.",
    title: "Technology that",
    highlight: "moves property",
    intro:
      "From property listing portals to lead-generating ad campaigns, we help developers, agencies and brokers showcase projects beautifully and turn online interest into site visits and sales.",
    badges: ["Listing portals", "Lead generation", "Virtual tours"],
    challenges: [
      { icon: "search", title: "Low online visibility", desc: "Buyers start online — if your projects don't show up, competitors win the enquiry.", fix: "SEO-optimised project pages and local search strategy so buyers find you first." },
      { icon: "users", title: "Unqualified leads", desc: "Portals and ads bring volume, but too few serious buyers.", fix: "Targeted campaigns and smart enquiry forms that filter by budget, location and intent." },
      { icon: "layout", title: "Outdated listings", desc: "Static brochures and slow sites fail to showcase premium properties.", fix: "Modern listing pages with galleries, floor plans and virtual tours that sell the space." },
      { icon: "clock", title: "Slow follow-up", desc: "Leads go cold when enquiries sit in inboxes and spreadsheets.", fix: "Instant lead alerts to WhatsApp and a simple CRM so no enquiry goes cold." },
    ],
    services: [
      { solution: "website-development", desc: "Premium project and agency websites with rich galleries, floor plans, maps and enquiry forms on every page.", points: ["Project microsites", "Floor plans & galleries", "Location maps"] },
      { solution: "custom-software", desc: "Property listing portals and lightweight CRMs that track every lead from first click to site visit.", points: ["Listing management", "Lead CRM", "Agent dashboards"] },
      { solution: "digital-marketing", desc: "Targeted Meta and Google campaigns that reach buyers by location, budget and intent.", points: ["Project launch campaigns", "Retargeting", "Lead forms"] },
      { solution: "seo", desc: "Rank for \"apartments in [city]\" and location searches that buyers actually use.", points: ["Local SEO", "Location landing pages", "Google Business Profile"] },
      { solution: "mobile-app-development", desc: "Apps for buyers to browse, shortlist and book visits — and for agents to manage leads on the go.", points: ["Property search", "Site visit booking", "Push alerts"] },
    ],
    builds: [
      { icon: "building", title: "Property Listing Portals", desc: "Search, filter and compare properties with rich media." },
      { icon: "layout", title: "Project Microsites", desc: "Launch-ready sites for each new development." },
      { icon: "media", title: "Virtual Tours & Galleries", desc: "Immersive walkthroughs that pre-qualify buyers." },
      { icon: "users", title: "Lead CRM", desc: "Capture, assign and follow up on every enquiry." },
      { icon: "calendar", title: "Site Visit Booking", desc: "Let buyers pick a slot online, synced to your team." },
      { icon: "megaphone", title: "Launch Campaigns", desc: "Ads and landing pages that fill your sales funnel." },
    ],
    outcomes: [
      "More qualified buyer enquiries",
      "Faster lead response times",
      "Premium online brand presence",
      "Higher rankings for local searches",
      "Every lead tracked in one place",
      "Lower cost per site visit",
    ],
    faqs: [
      { q: "Can you build a portal with search and filters?", a: "Yes — we build listing portals with search by location, budget, type and amenities, plus an admin panel to manage listings." },
      { q: "Do you run ads for new project launches?", a: "We plan and run launch campaigns on Google and Meta with dedicated landing pages to capture leads." },
      { q: "Can leads go straight to our sales team?", a: "Leads can be routed instantly to your CRM, email or WhatsApp so your team can follow up in minutes." },
    ],
  },
  {
    slug: "education",
    name: "Education",
    icon: "cap",
    tagline: "Websites, learning platforms and admissions marketing.",
    title: "Digital tools that",
    highlight: "power learning",
    intro:
      "We help schools, colleges, coaching centres and ed-tech startups attract students, run classes online and simplify administration with modern websites, apps and learning platforms.",
    badges: ["Admissions", "Online learning", "Student portals"],
    challenges: [
      { icon: "users", title: "Admissions competition", desc: "Parents and students compare many institutions online before applying.", fix: "A standout website and admission campaigns that put your institution ahead." },
      { icon: "media", title: "Moving learning online", desc: "Live and recorded classes need a reliable, easy platform.", fix: "An easy learning platform for live classes, recordings and assignments." },
      { icon: "gear", title: "Manual administration", desc: "Fees, attendance and results handled on paper or spreadsheets.", fix: "Digital fee, attendance and results management that saves staff hours." },
      { icon: "chat", title: "Parent communication", desc: "Keeping parents informed takes time and scattered tools.", fix: "A parent app and portal with notices, progress and instant updates." },
    ],
    services: [
      { solution: "website-development", desc: "Informative, trustworthy institution websites with courses, faculty, events and online admission forms.", points: ["Course pages", "Online admissions", "Events & news"] },
      { solution: "custom-software", desc: "Learning management systems, student portals and admin tools for fees, attendance and results.", points: ["LMS", "Fee management", "Results portal"] },
      { solution: "mobile-app-development", desc: "Apps for students and parents with timetables, notices, homework and live class access.", points: ["Timetables & notices", "Live classes", "Parent updates"] },
      { solution: "digital-marketing", desc: "Admission-season campaigns that reach the right students and parents in your area.", points: ["Admission campaigns", "Social media", "Lead nurturing"] },
      { solution: "seo", desc: "Rank for course and location searches so students find you first.", points: ["Course keywords", "Local SEO", "Content marketing"] },
    ],
    builds: [
      { icon: "cap", title: "Learning Management Systems", desc: "Courses, lessons, quizzes and progress tracking." },
      { icon: "media", title: "Live & Recorded Classes", desc: "Stream classes and build a video library." },
      { icon: "users", title: "Student & Parent Portals", desc: "Results, attendance and notices in one login." },
      { icon: "dollar", title: "Online Fee Payments", desc: "Secure payments with automatic receipts." },
      { icon: "layout", title: "Admission Websites", desc: "Course info and online application forms." },
      { icon: "chart", title: "Admin Dashboards", desc: "Real-time view of enrolments and performance." },
    ],
    outcomes: [
      "More admission enquiries",
      "Classes accessible anywhere",
      "Less paperwork for staff",
      "Happier, better-informed parents",
      "Faster, secure fee collection",
      "A modern, trusted brand",
    ],
    faqs: [
      { q: "Can you build a full LMS for our institute?", a: "Yes — courses, video lessons, quizzes, assignments and progress tracking, tailored to how you teach." },
      { q: "Can parents pay fees online?", a: "We integrate secure payment gateways with automatic receipts and fee reminders." },
      { q: "Do you help with admission season marketing?", a: "We run targeted campaigns and landing pages timed around your admission calendar." },
    ],
  },
  {
    slug: "healthcare",
    name: "Healthcare",
    icon: "medical",
    tagline: "Patient-friendly websites, booking and health apps.",
    title: "Better care through",
    highlight: "technology",
    intro:
      "We help clinics, hospitals, labs and health startups make care easier to access — with patient-friendly websites, online booking, telehealth and secure management systems.",
    badges: ["Online booking", "Telehealth", "Secure data"],
    challenges: [
      { icon: "calendar", title: "Phone-only appointments", desc: "Busy front desks and missed calls mean lost patients.", fix: "24/7 online booking with automatic confirmations and reminders." },
      { icon: "search", title: "Hard to find online", desc: "Patients search for doctors and treatments nearby — and choose who they find.", fix: "Local SEO and treatment pages that rank for nearby patient searches." },
      { icon: "lock", title: "Sensitive data", desc: "Patient information must be handled securely and responsibly.", fix: "Encrypted, role-based systems designed with patient privacy in mind." },
      { icon: "gear", title: "Disconnected systems", desc: "Records, billing and scheduling spread across different tools.", fix: "One clinic management system for scheduling, records and billing." },
    ],
    services: [
      { solution: "website-development", desc: "Clean, trustworthy websites with doctor profiles, treatments, timings and easy appointment booking.", points: ["Doctor profiles", "Treatment pages", "Online booking"] },
      { solution: "mobile-app-development", desc: "Patient apps for booking, reports, reminders and video consultations.", points: ["Appointment booking", "Lab reports", "Video consults"] },
      { solution: "custom-software", desc: "Clinic management systems for scheduling, patient records and billing — with secure, role-based access.", points: ["Scheduling", "Patient records", "Billing"] },
      { solution: "seo", desc: "Rank for \"doctor near me\" and treatment searches in your area.", points: ["Local SEO", "Treatment content", "Google Business Profile"] },
      { solution: "digital-marketing", desc: "Responsible, informative campaigns that build trust and bring in new patients.", points: ["Awareness campaigns", "Health content", "Reviews strategy"] },
    ],
    builds: [
      { icon: "calendar", title: "Appointment Booking", desc: "Real-time slots, confirmations and reminders." },
      { icon: "media", title: "Telehealth Consultations", desc: "Secure video visits from any device." },
      { icon: "database", title: "Patient Records", desc: "Organised, secure records with controlled access." },
      { icon: "mail", title: "Reports & Reminders", desc: "Share lab reports and send follow-up reminders." },
      { icon: "dollar", title: "Billing & Payments", desc: "Invoices and online payments in one flow." },
      { icon: "pin", title: "Multi-branch Websites", desc: "Locations, timings and doctors for every branch." },
    ],
    outcomes: [
      "More online appointments",
      "Fewer missed calls and no-shows",
      "Secure handling of patient data",
      "Better visibility in local search",
      "Less admin for front-desk staff",
      "A trusted, professional presence",
    ],
    faqs: [
      { q: "Can patients book appointments online?", a: "Yes — patients pick a doctor and time slot, get instant confirmation and automatic reminders." },
      { q: "How do you keep patient data secure?", a: "We use encrypted connections, role-based access and secure hosting, and design systems to follow applicable data-protection requirements." },
      { q: "Can you add video consultations?", a: "We can build or integrate secure telehealth video calls into your website or app." },
    ],
  },
  {
    slug: "fintech",
    name: "Fintech",
    icon: "dollar",
    tagline: "Secure, scalable platforms for modern finance.",
    title: "Secure platforms for",
    highlight: "modern finance",
    intro:
      "We help fintech startups and financial businesses build secure web and mobile products, clear dashboards and trustworthy brands — engineered for reliability from day one.",
    badges: ["Bank-grade security", "Payments", "Dashboards"],
    challenges: [
      { icon: "lock", title: "Security & trust", desc: "Users won't share money or data with products that feel unsafe.", fix: "Security built in from day one, with a polished interface that builds confidence." },
      { icon: "bolt", title: "Performance at scale", desc: "Transactions and data must stay fast as users grow.", fix: "Scalable cloud architecture and optimised APIs that stay fast as you grow." },
      { icon: "layout", title: "Complex made simple", desc: "Financial products need interfaces anyone can understand.", fix: "Clear, user-tested interfaces that make financial tasks effortless." },
      { icon: "link", title: "Many integrations", desc: "Payment gateways, banking APIs and KYC providers must work together.", fix: "Reliable integrations with payment gateways, banking APIs and KYC providers." },
    ],
    services: [
      { solution: "custom-software", desc: "Secure web platforms, admin consoles and APIs built for transactions, reporting and compliance workflows.", points: ["Transaction systems", "Admin consoles", "Secure APIs"] },
      { solution: "mobile-app-development", desc: "Fast, intuitive finance apps with secure login, payments and real-time updates.", points: ["Secure auth", "Payments", "Real-time alerts"] },
      { solution: "website-development", desc: "Credible product websites that explain your offering clearly and convert visitors into sign-ups.", points: ["Product pages", "Pricing & calculators", "Sign-up flows"] },
      { solution: "digital-marketing", desc: "Acquisition campaigns that grow sign-ups while keeping cost per user in check.", points: ["App install campaigns", "Retargeting", "Content"] },
      { solution: "seo", desc: "Educational content and SEO that build authority on finance topics.", points: ["Topic authority", "Calculators & tools", "Technical SEO"] },
    ],
    builds: [
      { icon: "dollar", title: "Payment Integrations", desc: "UPI, cards and gateways wired in securely." },
      { icon: "chart", title: "Financial Dashboards", desc: "Clear, real-time views of balances and activity." },
      { icon: "lock", title: "Secure Onboarding", desc: "Smooth sign-up with KYC provider integration." },
      { icon: "mobile", title: "Finance Apps", desc: "Wallets, lending and investment apps." },
      { icon: "gear", title: "Admin & Back-office", desc: "Tools for operations, support and reporting." },
      { icon: "database", title: "Scalable Backends", desc: "Reliable APIs and data built to grow." },
    ],
    outcomes: [
      "Products users trust with their money",
      "Reliable performance as you scale",
      "Simpler, clearer user journeys",
      "Faster integration with partners",
      "More sign-ups and activations",
      "Secure, maintainable codebase",
    ],
    faqs: [
      { q: "How do you approach security?", a: "Security is built in from the start — encrypted data, secure authentication, role-based access, audit logs and regular reviews." },
      { q: "Can you integrate payment gateways and KYC?", a: "Yes, we integrate popular payment gateways, UPI and KYC/verification providers." },
      { q: "Can you build an MVP first?", a: "We often start with a focused MVP to validate the product, then scale in phases." },
    ],
  },
  {
    slug: "media-entertainment",
    name: "Media & Entertainment",
    icon: "media",
    tagline: "Content platforms and campaigns that grow audiences.",
    title: "Platforms that",
    highlight: "grow audiences",
    intro:
      "We help publishers, creators, studios and event companies reach bigger audiences with fast content platforms, streaming experiences and social-first marketing.",
    badges: ["Streaming", "Content platforms", "Social growth"],
    challenges: [
      { icon: "bolt", title: "Heavy media, slow sites", desc: "Video and images slow sites down and drive visitors away.", fix: "Optimised media delivery and fast platforms that keep viewers watching." },
      { icon: "users", title: "Audience growth", desc: "Standing out on crowded social feeds is harder than ever.", fix: "Social-first content and campaigns designed to grow engaged followers." },
      { icon: "dollar", title: "Monetisation", desc: "Turning views into subscriptions, tickets or ad revenue.", fix: "Subscriptions, paywalls and ticketing that turn views into revenue." },
      { icon: "layout", title: "Publishing at speed", desc: "Teams need to publish fresh content quickly and easily.", fix: "A simple CMS so your team can write, schedule and publish in minutes." },
    ],
    services: [
      { solution: "website-development", desc: "Fast, media-rich websites and publishing platforms with an easy CMS for your editorial team.", points: ["News & blog CMS", "Galleries", "Optimised media"] },
      { solution: "mobile-app-development", desc: "Streaming and content apps with personalised feeds, offline viewing and notifications.", points: ["Video streaming", "Personalised feeds", "Push alerts"] },
      { solution: "digital-marketing", desc: "Social-first campaigns, reels and paid promotion that grow followers and engagement.", points: ["Social content", "Influencer campaigns", "Paid promotion"] },
      { solution: "custom-software", desc: "Subscriptions, ticketing and content management systems tailored to your model.", points: ["Subscriptions", "Ticketing", "Rights management"] },
      { solution: "seo", desc: "Get articles and videos discovered through search and Google News.", points: ["News SEO", "Video SEO", "Content strategy"] },
    ],
    builds: [
      { icon: "media", title: "Streaming Platforms", desc: "Video and audio delivered smoothly on any device." },
      { icon: "layout", title: "Publishing CMS", desc: "Write, schedule and publish content in minutes." },
      { icon: "dollar", title: "Subscriptions & Paywalls", desc: "Recurring revenue with flexible plans." },
      { icon: "calendar", title: "Event Ticketing", desc: "Sell tickets online with QR check-in." },
      { icon: "users", title: "Community Features", desc: "Comments, profiles and fan engagement." },
      { icon: "megaphone", title: "Social Campaigns", desc: "Content and ads that grow your following." },
    ],
    outcomes: [
      "Faster sites that keep viewers watching",
      "Bigger, more engaged audiences",
      "New recurring revenue streams",
      "Quicker publishing for your team",
      "Better discovery in search",
      "One partner for tech and marketing",
    ],
    faqs: [
      { q: "Can you build a video streaming platform?", a: "Yes — we build streaming websites and apps using reliable video hosting and delivery services." },
      { q: "Do you create social media content?", a: "Our team plans and produces posts, reels and campaigns tailored to each platform." },
      { q: "Can we sell subscriptions or tickets?", a: "We integrate subscriptions, paywalls and ticketing with secure online payments." },
    ],
  },
  {
    slug: "logistics",
    name: "Logistics",
    icon: "truck",
    tagline: "Tracking, fleet and operations software that scales.",
    title: "Smarter software for",
    highlight: "logistics",
    intro:
      "We help logistics, courier and transport companies run tighter operations with shipment tracking, fleet management, driver apps and websites that win new B2B clients.",
    badges: ["Live tracking", "Fleet management", "Driver apps"],
    challenges: [
      { icon: "pin", title: "No real-time visibility", desc: "Customers and managers can't see where shipments are.", fix: "Live shipment tracking for customers, managers and drivers." },
      { icon: "gear", title: "Manual dispatching", desc: "Phone calls and spreadsheets slow down every delivery.", fix: "Automated dispatch that assigns jobs to the right driver instantly." },
      { icon: "chat", title: "Constant status calls", desc: "Support teams spend hours answering \"where is my order?\"", fix: "Self-service tracking pages and automatic status notifications." },
      { icon: "chart", title: "Little data to optimise", desc: "Without data, routes and costs are hard to improve.", fix: "Operations dashboards that reveal delays, costs and route improvements." },
    ],
    services: [
      { solution: "custom-software", desc: "Shipment tracking, dispatch and fleet management systems with real-time dashboards.", points: ["Shipment tracking", "Dispatch system", "Fleet dashboard"] },
      { solution: "mobile-app-development", desc: "Driver apps with routes, proof of delivery and live location — plus customer tracking apps.", points: ["Driver app", "Proof of delivery", "Live location"] },
      { solution: "website-development", desc: "Professional company websites with service details, quote requests and a public tracking page.", points: ["Quote requests", "Tracking page", "Service areas"] },
      { solution: "seo", desc: "Rank for logistics and courier searches in the regions you serve.", points: ["Local SEO", "Service pages", "B2B keywords"] },
      { solution: "digital-marketing", desc: "B2B campaigns on LinkedIn and Google that bring in business clients.", points: ["LinkedIn ads", "Google Ads", "Lead nurturing"] },
    ],
    builds: [
      { icon: "pin", title: "Real-time Tracking", desc: "Live shipment status for customers and staff." },
      { icon: "truck", title: "Fleet Management", desc: "Vehicles, drivers and maintenance in one view." },
      { icon: "mobile", title: "Driver Apps", desc: "Routes, updates and proof of delivery." },
      { icon: "gear", title: "Dispatch Automation", desc: "Assign jobs automatically to the right driver." },
      { icon: "chart", title: "Operations Dashboards", desc: "Deliveries, delays and costs at a glance." },
      { icon: "link", title: "Client Integrations", desc: "Connect with e-commerce stores and ERPs." },
    ],
    outcomes: [
      "Full visibility of every shipment",
      "Fewer \"where is my order\" calls",
      "Faster, smarter dispatching",
      "Data to optimise routes and costs",
      "More B2B enquiries",
      "Systems that scale with your fleet",
    ],
    faqs: [
      { q: "Can customers track shipments live?", a: "Yes — we build tracking pages and apps that show live status and location updates." },
      { q: "Do drivers need a special app?", a: "We build simple driver apps for Android and iOS with routes, status updates and proof of delivery." },
      { q: "Can it integrate with our existing systems?", a: "We integrate with ERPs, e-commerce platforms and third-party APIs you already use." },
    ],
  },
  {
    slug: "construction",
    name: "Construction",
    icon: "construction",
    tagline: "Project management tools and websites that win tenders.",
    title: "Building better with",
    highlight: "technology",
    intro:
      "We help construction companies and contractors showcase their work, win more projects and manage sites efficiently with portfolio websites, project management tools and field apps.",
    badges: ["Project tracking", "Portfolio sites", "Field apps"],
    challenges: [
      { icon: "layout", title: "Work not showcased", desc: "Great completed projects stay invisible to future clients.", fix: "A portfolio website with project galleries and case studies that win tenders." },
      { icon: "clock", title: "Delays & overruns", desc: "Without clear tracking, schedules and budgets slip.", fix: "Project tracking for schedules, milestones and budgets across every site." },
      { icon: "chat", title: "Site-to-office gaps", desc: "Updates from site teams arrive late or get lost.", fix: "Field apps for daily reports, photos and issues — synced to the office instantly." },
      { icon: "database", title: "Scattered documents", desc: "Drawings, approvals and invoices live in many places.", fix: "A central, secure document hub for drawings, approvals and invoices." },
    ],
    services: [
      { solution: "website-development", desc: "Portfolio websites that showcase completed projects, capabilities and certifications to win new clients.", points: ["Project portfolio", "Capabilities", "Enquiry forms"] },
      { solution: "custom-software", desc: "Project management tools for schedules, budgets, materials and documents across every site.", points: ["Scheduling", "Budget tracking", "Document hub"] },
      { solution: "mobile-app-development", desc: "Field apps for daily reports, photos, attendance and issue tracking from site.", points: ["Daily reports", "Site photos", "Attendance"] },
      { solution: "seo", desc: "Rank for construction services in the areas you build.", points: ["Local SEO", "Service pages", "Project case studies"] },
      { solution: "digital-marketing", desc: "Campaigns that put your brand in front of developers, businesses and homeowners.", points: ["Google Ads", "LinkedIn", "Brand content"] },
    ],
    builds: [
      { icon: "layout", title: "Portfolio Websites", desc: "Showcase projects with photos and case studies." },
      { icon: "calendar", title: "Project Scheduling", desc: "Timelines and milestones for every site." },
      { icon: "dollar", title: "Budget & Cost Tracking", desc: "Know where every rupee is going." },
      { icon: "mobile", title: "Site Reporting Apps", desc: "Daily updates and photos from the field." },
      { icon: "database", title: "Document Management", desc: "Drawings and approvals in one secure place." },
      { icon: "users", title: "Client Portals", desc: "Keep clients updated on progress automatically." },
    ],
    outcomes: [
      "A portfolio that wins new projects",
      "Better control of schedules & budgets",
      "Real-time updates from every site",
      "All documents in one place",
      "Happier, better-informed clients",
      "More enquiries from search",
    ],
    faqs: [
      { q: "Can site teams use the app offline?", a: "We can build field apps that save data offline and sync when the connection returns." },
      { q: "Can clients see project progress?", a: "Yes — client portals can show milestones, photos and updates automatically." },
      { q: "Can you showcase our past projects?", a: "We design portfolio websites with galleries and case studies that highlight your best work." },
    ],
  },
  {
    slug: "debate-academy",
    name: "Debate Academy",
    icon: "debate",
    tagline: "Platforms for training, tournaments and student growth.",
    title: "Digital platforms for",
    highlight: "debate academies",
    intro:
      "We help debate and public-speaking academies run classes, manage tournaments and grow enrolments with dedicated web platforms, apps and marketing.",
    badges: ["Tournament tools", "Online classes", "Enrolments"],
    challenges: [
      { icon: "calendar", title: "Tournament admin", desc: "Draws, rounds and results managed by hand take hours.", fix: "A tournament system that automates registrations, draws, rounds and results." },
      { icon: "media", title: "Online training", desc: "Students need classes, recordings and feedback in one place.", fix: "One platform for live classes, recordings, practice material and feedback." },
      { icon: "users", title: "Growing enrolments", desc: "Reaching students and parents beyond word of mouth.", fix: "Targeted campaigns and a strong website that fill every new batch." },
      { icon: "chart", title: "Tracking progress", desc: "Hard to measure each speaker's growth over time.", fix: "Speaker scorecards and progress dashboards for every student." },
    ],
    services: [
      { solution: "custom-software", desc: "Tournament management systems for registrations, draws, rounds, judging and results.", points: ["Registrations", "Draws & rounds", "Results & rankings"] },
      { solution: "website-development", desc: "Academy websites with programmes, coaches, achievements and online enrolment.", points: ["Programme pages", "Coach profiles", "Online enrolment"] },
      { solution: "mobile-app-development", desc: "Apps for students to join classes, watch recordings and track their progress.", points: ["Class access", "Recordings", "Progress tracking"] },
      { solution: "digital-marketing", desc: "Campaigns that reach students and parents and fill your next batch.", points: ["Enrolment campaigns", "Social media", "Event promotion"] },
      { solution: "seo", desc: "Rank for debate and public-speaking classes in your city.", points: ["Local SEO", "Course pages", "Blog content"] },
    ],
    builds: [
      { icon: "calendar", title: "Tournament Management", desc: "Registrations, draws, rounds and live results." },
      { icon: "media", title: "Online Classes", desc: "Live sessions and a library of recordings." },
      { icon: "chart", title: "Speaker Progress", desc: "Scores and feedback tracked over time." },
      { icon: "users", title: "Student Portals", desc: "Schedules, materials and announcements." },
      { icon: "dollar", title: "Online Payments", desc: "Fees and tournament entries paid online." },
      { icon: "megaphone", title: "Event Promotion", desc: "Campaigns that fill tournaments and batches." },
    ],
    outcomes: [
      "Tournaments run in a fraction of the time",
      "Classes accessible from anywhere",
      "Clear progress for every student",
      "More enrolments each batch",
      "Simple online payments",
      "A professional academy brand",
    ],
    faqs: [
      { q: "Can you build a tournament tab system?", a: "Yes — registrations, team and speaker draws, rounds, judge allocation and live results can all be handled online." },
      { q: "Can students attend classes online?", a: "We build platforms for live classes, recordings and practice material in one place." },
      { q: "Do you help promote our tournaments?", a: "We run social and paid campaigns to promote tournaments and new batches." },
    ],
  },
];

export const getIndustry = (slug) => industries.find((i) => i.slug === slug);
